[book]
title = "rust-supervisor 手册"
authors = ["developerworks"]
description = "中文 rust-supervisor 项目手册."
language = "zh-CN"
src = "."

[build]
create-missing = false

[output.html]
git-repository-url = "https://github.com/developerworks/rust-supervisor"
edit-url-template = "https://github.com/developerworks/rust-supervisor/edit/main/manual/zh/{path}"
site-url = "/rust-supervisor/zh/"
additional-css = ["../theme/left-aligned.css"]
